# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('sea_level', models.FloatField()),
                ('grnd_level', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('snow', models.FloatField()),
                ('rain', models.FloatField()),
                ('dt_txt', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.City')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.WeatherDescription'),
        ),
        migrations.AddField(
            model_name='weather',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.WeatherGroup'),
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.WeatherIcon'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.Weather'),
        ),
    ]
